# Generated by Django 2.2.4 on 2019-10-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.CharField(blank=True, default=' ', max_length=350),
        ),
    ]
