# Generated by Django 2.2.4 on 2019-10-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
