# Generated by Django 3.0.8 on 2020-08-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200809_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_earned',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_spent',
        ),
    ]
