# Generated by Django 2.2.4 on 2019-10-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_earned',
            field=models.FloatField(null=True),
        ),
    ]
