# Generated by Django 2.2.4 on 2019-10-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_total_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_earned',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
