# Generated by Django 2.2.4 on 2019-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191024_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_spent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
