# Generated by Django 2.2.4 on 2019-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_total_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_earned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_spent',
            field=models.FloatField(default=0),
        ),
    ]
