# Generated by Django 2.2.4 on 2019-10-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_app', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=350)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=350)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Client')),
                ('items', models.ManyToManyField(to='invoices.Item')),
            ],
        ),
    ]
