# Generated by Django 2.2.4 on 2019-11-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_app', '0001_initial'),
        ('company_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.IntegerField(default=0, null=True)),
                ('total_unit_price', models.FloatField(default=0, null=True)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('notes', models.CharField(blank=True, max_length=350)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manage_app.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company_panel.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=350)),
                ('unit_price', models.FloatField(default=0.0)),
                ('amount', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company_panel.Company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='invoices.Invoice')),
            ],
        ),
    ]
