# Generated by Django 2.2.4 on 2019-10-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_panel', '0006_auto_20191025_1539'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company_panel.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company_panel.Company'),
            preserve_default=False,
        ),
    ]
