# Generated by Django 2.2.4 on 2019-10-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20191025_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
