# Generated by Django 3.0.8 on 2020-08-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20191207_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['company', 'date'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['company', 'invoice'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
