# Generated by Django 2.2.4 on 2019-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20191026_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
