# Generated by Django 2.2.4 on 2019-10-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_auto_20191026_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_price',
            new_name='total_unit_price',
        ),
    ]
