# Generated by Django 2.2.4 on 2019-10-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20191026_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
