# Generated by Django 2.2.4 on 2019-10-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_invoice_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
