# Generated by Django 2.2.4 on 2019-10-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
