# Generated by Django 2.2.4 on 2019-08-30 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('timesheets_app', '0002_auto_20190829_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_id', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
