# Generated by Django 2.2.4 on 2019-08-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0003_auto_20190830_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
