# Generated by Django 2.2.4 on 2019-09-01 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2019, 9, 1, 16, 19, 1, 667856, tzinfo=utc)),
        ),
    ]
