# Generated by Django 2.2.4 on 2019-09-18 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0005_company_date_of_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_id', models.BigIntegerField()),
                ('task_id', models.BigIntegerField()),
                ('notes', models.CharField(blank=True, max_length=350)),
                ('timer', models.TimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 12, 21, 4, 397330, tzinfo=utc)),
        ),
    ]
