# Generated by Django 2.2.4 on 2019-09-18 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0006_auto_20190918_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 18)),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 13, 14, 49, 847515, tzinfo=utc)),
        ),
    ]
