# Generated by Django 2.2.4 on 2019-09-18 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0007_auto_20190918_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2019, 9, 18)),
        ),
    ]
