# Generated by Django 2.2.4 on 2019-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0008_auto_20190918_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timer',
            field=models.TimeField(default='0:00'),
        ),
    ]
