# Generated by Django 2.2.4 on 2019-09-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0010_auto_20190919_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_id', models.BigIntegerField()),
                ('default_hourly_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='task_id',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets_app.Client')),
                ('tasks', models.ManyToManyField(to='timesheets_app.Task')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timesheets_app.Project'),
        ),
        migrations.AddField(
            model_name='entry',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timesheets_app.Task'),
        ),
    ]
