# Generated by Django 2.2.4 on 2019-09-21 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0011_auto_20190919_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='company_id',
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timesheets_app.Company'),
        ),
        migrations.AddField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timesheets_app.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timesheets_app.Company'),
        ),
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timesheets_app.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2019, 9, 21)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 21)),
        ),
    ]
