# Generated by Django 2.2.4 on 2019-09-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0013_auto_20190921_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets_app.Project'),
        ),
    ]
