# Generated by Django 2.2.4 on 2019-09-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0015_auto_20190921_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timer',
            field=models.TimeField(blank=True, default='0:00'),
        ),
    ]
