# Generated by Django 2.2.4 on 2019-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0017_auto_20190921_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='timer',
            field=models.TimeField(),
        ),
    ]
