# Generated by Django 2.2.4 on 2019-09-22 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0018_auto_20190921_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2019, 9, 22, 12, 32, 25, 144881, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2019, 9, 22)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date(2019, 9, 22)),
        ),
    ]
