# Generated by Django 2.2.4 on 2019-09-22 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0019_auto_20190922_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='timer',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
