# Generated by Django 2.2.4 on 2019-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets_app', '0020_auto_20190922_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
