# Generated by Django 2.2.4 on 2019-08-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
