# Generated by Django 2.2.4 on 2019-11-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_panel', '0003_auto_20191125_1506'),
        ('authentication', '0002_auto_20191105_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company_panel.Role'),
        ),
    ]
