# Generated by Django 2.2.4 on 2019-12-07 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date(2019, 12, 7)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, default=' ', max_length=350),
        ),
    ]
