# Generated by Django 2.2.4 on 2019-10-23 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_auto_20191002_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date(2019, 10, 23)),
        ),
    ]
