# Generated by Django 3.0.8 on 2020-08-09 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_auto_20191207_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['company', 'user', 'date'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date(2020, 8, 9)),
        ),
    ]
