# Generated by Django 3.0.8 on 2020-08-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200818_1851'),
        ('times', '0004_auto_20200818_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='projects.Project'),
        ),
    ]
