# Generated by Django 2.2.4 on 2019-09-29 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_of_creation', models.DateField(default=datetime.date(2019, 9, 29))),
            ],
        ),
    ]
