# Generated by Django 2.2.4 on 2019-11-25 12:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_panel', '0002_auto_20191105_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2019, 11, 25)),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('user_info_access', models.BooleanField()),
                ('detailed_project_info_access', models.BooleanField()),
                ('project_manage_access', models.BooleanField()),
                ('invite_user_access', models.BooleanField()),
                ('expenses_manage_access', models.BooleanField()),
                ('invoices_manage_access', models.BooleanField()),
                ('client_manage_access', models.BooleanField()),
                ('task_manage_access', models.BooleanField()),
                ('expense_category_manage_access', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company_panel.Company')),
            ],
        ),
    ]
