# Generated by Django 2.2.4 on 2019-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_panel', '0003_auto_20191125_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='kick_user_access',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
