# Generated by Django 2.2.4 on 2019-10-24 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_panel', '0004_auto_20191023_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2019, 10, 24)),
        ),
    ]
