# Generated by Django 2.2.4 on 2019-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_panel', '0008_auto_20191125_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='client_manage_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='detailed_project_info_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='edit_company_info_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='expense_category_manage_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='expenses_manage_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='invite_user_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='invoices_manage_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='kick_user_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='manage_roles_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='project_manage_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='task_manage_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_info_access',
            field=models.BooleanField(default=False),
        ),
    ]
