# Generated by Django 3.0.8 on 2020-08-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_panel', '0012_auto_20200818_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='expense_category_manage_access',
        ),
        migrations.RemoveField(
            model_name='role',
            name='expenses_manage_access',
        ),
    ]
