# Generated by Django 3.0.8 on 2020-08-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_panel', '0013_auto_20200818_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='manage_hourly_rates_access',
            field=models.BooleanField(default=False),
        ),
    ]
