# Generated by Django 2.2.4 on 2019-12-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='default_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
