# Generated by Django 3.0.8 on 2020-08-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_auto_20191207_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['company', 'name'], 'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expenses Categories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company', 'name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['company', 'name'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
