# Generated by Django 3.0.8 on 2020-08-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0003_auto_20200809_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
