# Generated by Django 3.0.8 on 2020-08-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0005_auto_20200818_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='default_hourly_rate',
        ),
    ]
