# Generated by Django 3.0.8 on 2020-08-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0006_remove_task_default_hourly_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
