# Generated by Django 3.0.8 on 2020-08-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['company'], 'verbose_name': 'Invitation', 'verbose_name_plural': 'Invitations'},
        ),
    ]
